scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: pole_right
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -1.78
        upper_angle: -1.63
    filter2:
      name: pole_left
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 1.65
        upper_angle: 1.80
